# Generated by Django 3.2.4 on 2021-06-25 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prtc', models.CharField(max_length=300)),
                ('method', models.CharField(choices=[('C', 'CREDIT'), ('D', 'DEBIT')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('chq_no', models.CharField(max_length=20)),
                ('chq_date', models.DateField()),
                ('bank', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='cash_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prtc', models.CharField(max_length=300)),
                ('method', models.CharField(choices=[('C', 'CREDIT'), ('D', 'DEBIT')], max_length=1)),
                ('reference', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='client_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('contact_1', models.CharField(max_length=20)),
                ('contact_2', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Company', max_length=40)),
                ('address', models.TextField()),
                ('account_number', models.CharField(max_length=20)),
                ('contact_1', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=30)),
                ('invoice_template', models.IntegerField(default=0)),
                ('payroll_template', models.IntegerField(default=0)),
                ('footer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='employee_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=40)),
                ('is_regular', models.BooleanField(default=True)),
                ('department', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('contact_1', models.CharField(max_length=20)),
                ('contact_2', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=40)),
                ('is_married', models.CharField(max_length=10)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('emergency_name', models.CharField(max_length=20)),
                ('emergency_relation', models.CharField(max_length=10)),
                ('emergency_contact_1', models.CharField(max_length=20)),
                ('emergency_contact_2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=8, unique=True)),
                ('working_days', models.IntegerField(default=26)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=15)),
                ('report_no', models.CharField(max_length=15)),
                ('report_date', models.DateField(default='0000-00-00')),
                ('invoice_no', models.CharField(max_length=15)),
                ('invoice_date', models.DateField(default='0000-00-00')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('recieved', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('due', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.client_info')),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('db', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_accountant', models.BooleanField(default=False)),
                ('is_hr', models.BooleanField(default=False)),
                ('is_marchent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='sales_criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_desc', models.CharField(max_length=80)),
                ('task_quantity', models.CharField(max_length=20)),
                ('task_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.sales')),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('medical', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('home', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('conveyance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('transport', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('others', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='handler.currency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.employee_info')),
            ],
        ),
        migrations.CreateModel(
            name='payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField(default=0)),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('medical', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('home', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('conveyance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('transport', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('others', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='handler.currency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.employee_info')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='handler.month')),
            ],
        ),
        migrations.CreateModel(
            name='currency_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=8)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=11)),
                ('time', models.TimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.currency')),
            ],
        ),
        migrations.AddField(
            model_name='client_info',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='handler.employee_info'),
        ),
        migrations.CreateModel(
            name='activity_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
