# Generated by Django 3.2.4 on 2021-06-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0002_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_log',
            name='method',
            field=models.CharField(choices=[('C', 'Create'), ('U', 'Update'), ('D', 'Delete')], default='v', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='account_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='bank',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='contact_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='department',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='emergency_contact_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='emergency_contact_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='emergency_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='emergency_relation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='id_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='is_married',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='permanent_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='present_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='role',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
