# Generated by Django 3.2.4 on 2021-06-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0004_auto_20210626_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='bank',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='contact_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='department',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='emergency_contact_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='emergency_contact_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='emergency_relation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='id_no',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='present_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='role',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
