# Generated by Django 3.2.4 on 2021-06-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0005_auto_20210626_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_log',
            name='user',
            field=models.IntegerField(),
        ),
    ]
