# Generated by Django 3.2.4 on 2021-06-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0006_alter_activity_log_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_log',
            name='username',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='role',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
