# Generated by Django 3.2.4 on 2021-06-27 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0007_auto_20210627_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_log',
            name='time',
        ),
        migrations.AddField(
            model_name='activity_log',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
