# Generated by Django 3.2.4 on 2021-06-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0013_auto_20210630_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_info',
            name='dept',
        ),
        migrations.AddField(
            model_name='employee_info',
            name='department',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
