# Generated by Django 3.2.4 on 2021-06-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0014_auto_20210630_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='department',
            field=models.IntegerField(blank=True),
        ),
    ]
