# Generated by Django 3.2.4 on 2021-07-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0015_alter_employee_info_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll_part',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='handler.employee_info'),
            preserve_default=False,
        ),
    ]
