# Generated by Django 3.2.4 on 2021-07-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0016_payroll_part_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_info',
            name='lead',
        ),
        migrations.AlterField(
            model_name='client_info',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='contact_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='contact_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='website',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
