# Generated by Django 3.2.4 on 2021-07-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0020_sales_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_criteria',
            old_name='task_cost',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='sales_criteria',
            old_name='task_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='sales_criteria',
            old_name='task_quantity',
            new_name='qtn',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='job_no',
        ),
        migrations.AddField(
            model_name='sales',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
