# Generated by Django 3.2.4 on 2021-07-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0021_auto_20210704_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash_book',
            name='reference',
        ),
        migrations.AddField(
            model_name='bank_book',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='handler.month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cash_book',
            name='comment',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cash_book',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='handler.month'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank_book',
            name='method',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='cash_book',
            name='method',
            field=models.CharField(max_length=1),
        ),
    ]
