# Generated by Django 3.2.4 on 2021-07-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0022_auto_20210706_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_book',
            name='bank',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='bank_book',
            name='chq_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='bank_book',
            name='chq_no',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='media/image'),
        ),
    ]
