# Generated by Django 3.2.4 on 2021-07-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0024_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('page_url', models.CharField(max_length=40)),
                ('thumb', models.ImageField(upload_to='templates_thumb')),
            ],
        ),
        migrations.CreateModel(
            name='tmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=40)),
                ('fontsize', models.IntegerField()),
                ('pagesize', models.IntegerField()),
                ('footertext', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to='logo'),
        ),
    ]
