# Generated by Django 3.2.4 on 2021-07-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0026_templates_isfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmp',
            name='orientation',
            field=models.CharField(choices=[('portrait', 'portrait'), ('landscape', 'landscape')], default='portrait', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tmp',
            name='pagesize',
            field=models.CharField(max_length=10),
        ),
    ]
