# Generated by Django 3.2.4 on 2021-07-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0027_auto_20210720_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmp',
            name='isfor',
            field=models.CharField(default='random', max_length=40),
        ),
        migrations.AlterField(
            model_name='tmp',
            name='orientation',
            field=models.CharField(max_length=10),
        ),
    ]
