# Generated by Django 3.2.4 on 2021-07-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0028_auto_20210723_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='company',
            name='invoice_template',
        ),
        migrations.RemoveField(
            model_name='company',
            name='payroll_template',
        ),
    ]
