# Generated by Django 3.2.4 on 2021-07-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0030_auto_20210724_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_info',
            name='face',
        ),
    ]
