# Generated by Django 3.2.4 on 2021-08-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0031_remove_employee_info_face'),
    ]

    operations = [
        migrations.DeleteModel(
            name='templates',
        ),
        migrations.RenameField(
            model_name='tmp',
            old_name='footertext',
            new_name='src_code',
        ),
        migrations.RemoveField(
            model_name='tmp',
            name='fontsize',
        ),
        migrations.RemoveField(
            model_name='tmp',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='tmp',
            name='page_url',
        ),
        migrations.RemoveField(
            model_name='tmp',
            name='pagesize',
        ),
        migrations.AlterField(
            model_name='currency_rate',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006')], max_length=5),
        ),
        migrations.AlterField(
            model_name='tmp',
            name='isfor',
            field=models.CharField(choices=[('I', 'Invoice'), ('PR', 'Payroll_Regular'), ('PR', 'Payroll_Casual'), ('CB', 'Cash_Book'), ('BB', 'Bank_Book')], max_length=40),
        ),
    ]
