# Generated by Django 3.2.4 on 2021-08-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0032_auto_20210824_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='messageforus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('recieved_at', models.DateField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='tmp',
            name='isfor',
            field=models.CharField(choices=[('I', 'Invoice'), ('PR', 'Payroll_Regular'), ('PC', 'Payroll_Casual'), ('CB', 'Cash_Book'), ('BB', 'Bank_Book')], max_length=40),
        ),
    ]
