# Generated by Django 3.2.4 on 2021-08-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0033_auto_20210828_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageforus',
            name='recieved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
